### ISSUE TITLE
can't convert fit File exported from FitFileRepairTool

### ISSUE THREAD

**Issue by streamtec** [mrihtar/Garmin-FIT#15]
Hello mrihtar,
I have a problem to convert a FIT-File exported from FitFileRepairTool (http://fitfilerepairtool.info/).
The FIT-File was original created as an export in BKOOL-Bike Trainer Software.
But it contains 2 Rounds, so I load this file inte the FitFileRepairTool, to concatinate the 2 Rounds to one. After this I make an export also into a new FIT-File.
When I start the pearl-script to convert the new File it stops whit an error-message:
"Use of uninitialized value in concatenation (.) or string at ./fit2slf_orig.pl line 258"
Can you anlyse this problem?
(See Fit-File inthe attachment)
[a5520321.fit.zip](https://github.com/mrihtar/Garmin-FIT/files/1523813/a5520321.fit.zip)

Best regards Walter

**Comment by mrihtar** [comment]
Hi!
Are you sure you sent me the right file? Because conversion of a5520321.fit seems quite OK (with all 3 scripts: fitdump, fit2slf and fit2gpx). It contains 1 route along the lake (direction north), length of 22.6 km. If you have older version of scripts, don't forget to do git pull or download the latest version (v2.11) from the releases tab.

**Comment by streamtec** [comment]
Hi,
sorry you are right. I download your latest version from git and it works.
Sorry, next time i will do this first.
Many thanks for your quick response.
Best regards Walter
