### ISSUE TITLE
Error when converting a fit file from wahoo element with actual firmware

### ISSUE THREAD

**Issue by streamtec** [mrihtar/Garmin-FIT#18]
Hello mrihtar,
today I want to convert a fit file from my wahoo elemnt.
There was an firmware update since last converting a file.
I get this error-message:
"Use of uninitialized value $prev_timestamp in subtraction (-) at ./fit2slf_orig.pl line 1438.
Illegal division by zero at ./fit2slf_orig.pl line 1446."
Can you have a look where's the problem?
I have attached the FIT-File. 
[ELEMNT.fit.zip](https://github.com/mrihtar/Garmin-FIT/files/2949412/ELEMNT.fit.zip)

**Comment by mrihtar** [comment]
The answer to Garmin's eternal question "Zero, or no zero values ..." was solved with an introduction of **_-z_** switch. So, for devices, which don't return latitude/longitude like yours, please use **_-z_** to allow zero values for latitude/longitude. Default will remain to ignore such records, because some other devices just **sometime** don't return these values and then the position "rubber bands". If you don't use **_-z_** for fit files from your device, you will get empty GPX/SLF files (headers only).

**Comment by streamtec** [comment]
Hello Matjaz,
many thank’s for your quick support.
