### ISSUE TITLE
Problem with time_created

### ISSUE THREAD

**Issue by flat-linex** [mrihtar/Garmin-FIT#28]
Hi, 

till last year the time_created element of the exported Garmin swim file had both a human readable date and a numeric version.
The latest file I downloaded however only provides me with the numeric version: how can I transform it to a date as before?

[5629129253.fit.zip](https://github.com/mrihtar/Garmin-FIT/files/5323170/5629129253.fit.zip)
 
Thankx a lot!

**Comment by mrihtar** [comment]
I added command line parameter -t \<offs\>, with which you can add arbitrary offset to timestamp stored in .fit file. You'll have to experiment with offset values to get what you want. For your file, -t 1600827700 will set the date to 4-Oct-2020.

This timestamp behavior is specific to Garmin Swim - see  [https://www.thisisant.com/forum/viewthread/4051/#4989](https://www.thisisant.com/forum/viewthread/4051/#4989)

Besides this fix, you won't get a lot of useful information out of a swim .fit file with fit2gpx/fit2slf, because these two conversion programs concentrate mostly on biking/running records and not on swimming records.
