### ISSUE TITLE
Failure importing input.slf into Sigma Data Center Version 4.0.11

### ISSUE THREAD

**Issue by Ottomo1975** [mrihtar/Garmin-FIT#3]
![screenshot_21](https://cloud.githubusercontent.com/assets/22867684/19417023/d254e102-93a1-11e6-8975-59f1dd957ba6.png)
@mrihtar: Great initiative and 100% what I´m looking since 1,5 years. 
Unfortunatelly import of the created .slf file didn´t work, see screenshot.
Any ideas what went wrong?

**Comment by mrihtar** [comment]
I think Sigma Data Center handles/stores (some?) dates in a local format and your locale is different than the one used in fit2slf (which generates format for the default locale "C"). That's why the error "could not convert string value to date" occurs. I could generalize the date formatting (in routine PrintSlfHeader, call to POSIX::strftime), but there is a problem with UTC offset, which is not added to the normal "%c" locale representation.

Could you please generate one log file from your Sigma Data Center to see what your format of date is?

You can also check if your converted log file imports successfully after you manually modify the date to your local format. Search for "fileDate", "dateCode" and "startDate" and fix the date format.

**Comment by Ottomo1975** [comment]
Hi,

thanks for your very quick response. Really appriciate that.

I modified the input.slf I´ve generated with the date format that I see when I create an .slf export from the Sigma Data Center.
But still get the same error.

I´ve attached mail a zip file containing an export from the Sigma Data Center and the generated input.slf.

Thanks again for your work and I would love to donate you some money If we could get this working.

Cheers

**Comment by mrihtar** [comment]
I've checked your input.slf and the problem is in "startDate" only. Are you sure "Sa Okt ..." is the right format? Shouldn't it be "Sam Okt ..." (a three letter day abbreviation)? If I use "Sat Oct" (as I am using default US locale), I can successfully import your file. The other file has default "C" format, so it didn't help much.

**Comment by Ottomo1975** [comment]
@mrihtar, i´ve change the date format in all 3 places ("fileDate", "dateCode" and "startDate") to the english 3 letter format (Sat ... Oct...) and now it works. Would it be possible to include this translation in your script?
