### ISSUE TITLE
No lap, No auto pause, wrong power

### ISSUE THREAD

**Issue by mpnegro** [mrihtar/Garmin-FIT#6]
Hi,
I convert a ride today with the "fit master", and I don't have a lap, no auto pause, and the power is wrong (I've a power metter) 
Can you help me with this?
Regards

**Comment by mrihtar** [comment]
If by converting you mean converting to Sigma log file, you currently won't get laps/pauses, because I didn't know the format. I will fix this as soon as possible (this is already covered in previous issue).

Power calculation with formulas as it's done in converter will almost always be different than the power measured with real power meter. That's why I included the possibility to tweak the power calculation with parameters in fit2slf.ini (see [Config (ini) File Syntax](https://github.com/mrihtar/Garmin-FIT/blob/master/config.md)). As you have a real power meter, you can adapt these parameters to follow real measurements as close as possible.

**Comment by mpnegro** [comment]
Hi,
Is not possible to make the converter to see if you have power values (by a power meter) and if not calculate the power? Something like if power in file use power from file else calculate power? (I'm not a programmer)

**Comment by mrihtar** [comment]
Sure, that would be best and of course it can be done, if you provide me with an example (or two) of such .fit file.

**Comment by mpnegro** [comment]
Have send you the files

**Comment by mrihtar** [comment]
This fixes the power issue, lap and auto-pause will be dealt in issue #5.
